import type { TimelinePhase } from "./particle-types";

export const PARTICLE_CONFIG = {
  initialShape: "theodore",
  desktopParticles: 5_000,
  wideDesktopParticles: 9_000,
  mobileParticles: 2_800,
  reducedMotionParticles: 1_600,
  mobileBreakpoint: 720,
  wideDesktopBreakpoint: 1_600,
  maxPixelRatio: 2,
  camera: {
    fov: 55,
    near: 0.1,
    far: 1_000,
    z: 130,
    parallaxX: 1.1,
    parallaxY: 0.65,
  },
  points: {
    size: 2.8,
    sizeMinimum: 1.5,
    sizeMaximum: 4.25,
    brightSize: 6.8,
    depthExponent: 1.35,
    sizeDepthExponent: 1.45,
    sizeVariationMinimum: 0.78,
    sizeVariationMaximum: 1.35,
    scatterOpacity: 0.68,
    wordOpacity: 0.98,
    ambientAnchorRatio: 0.17,
    brightStarRatio: 0.022,
    ambientOpacityMinimum: 0.08,
    ambientOpacityMaximum: 0.38,
    ambientAnchorBoost: 0.18,
    wordClarity: {
      ink: "#f4faff",
      colorBlend: 0.64,
      sizeBlend: 0.46,
      alphaBoost: 0.1,
      anchorOpacityAtWord: 0.86,
      anchorOpacityAtScatter: 0.96,
    },
    palette: {
      far: "#78b9e2",
      middle: "#b4dcf3",
      near: "#f5fbff",
      ice: "#78e3ff",
      warm: "#ffd28a",
      lavender: "#c9c4ff",
      warmRatio: 0.06,
      lavenderRatio: 0.035,
      iceRatio: 0.12,
      tonalVariation: 0.055,
    },
  },
  morph: {
    maximumDelay: 0.38,
    targetWidthRatio: 0.72,
    targetHeightRatio: 0.24,
    targetJitterRatio: 0.018,
  },
  pointer: {
    radius: 48,
    force: 80,
    spring: 12,
    damping: 9,
    maximumOffset: 12,
  },
  spatial: {
    wordDepth: 8,
    depthCurve: 2.4,
    dragThreshold: 7,
    dragTravelX: 180,
    dragTravelY: 150,
    yawSoftLimit: 3.5,
    yawHardLimit: 4.2,
    pitchSoftLimit: 2,
    pitchHardLimit: 2.4,
    releaseResponse: 0.5,
    releaseVelocityRetention: 0.18,
    maximumReleaseVelocity: 8,
    scatterPoseGain: 0.24,
    ambientPoseGain: 0.08,
    scatterRepulsionGain: 0.36,
    draggingRepulsionGain: 0.64,
  },
  ambient: {
    transitionResponse: 1.35,
    heroReturnResponse: 1.55,
    semanticResponse: 0.34,
    parallaxX: 0.34,
    parallaxY: 0.2,
    driftX: 1.9,
    driftY: 1.35,
    driftSpeedMinimum: 0.18,
    driftSpeedMaximum: 0.42,
    twinkleSpeedMinimum: 0.65,
    twinkleSpeedMaximum: 1.35,
    twinkleMinimum: 0.08,
    twinkleMaximum: 0.22,
    heroAnchorMotionGain: 0.92,
    heroAnchorTwinkleGain: 0.9,
    heroWordTwinkleGain: 0.18,
  },
} as const;

export const PARTICLE_TIMELINE: readonly TimelinePhase[] = [
  { kind: "hold", shape: "theodore", duration: 5.5 },
  { kind: "morph", to: "scatter", duration: 2.8 },
  { kind: "hold", shape: "scatter", duration: 1.2 },
  { kind: "morph", to: "ouyang", duration: 2.8 },
  { kind: "hold", shape: "ouyang", duration: 4.5 },
  { kind: "morph", to: "scatter", duration: 2.8 },
  { kind: "hold", shape: "scatter", duration: 1.2 },
  { kind: "morph", to: "theodore", duration: 2.8 },
];
