import type { TimelinePhase } from "./particle-types";

export const PARTICLE_CONFIG = {
  initialShape: "theodore",
  desktopParticles: 5_000,
  mobileParticles: 2_800,
  reducedMotionParticles: 1_600,
  mobileBreakpoint: 720,
  maxPixelRatio: 2,
  camera: {
    fov: 55,
    near: 0.1,
    far: 1_000,
    z: 130,
    parallaxX: 1.1,
    parallaxY: 0.65,
  },
  points: {
    size: 2.25,
    scatterOpacity: 0.38,
    wordOpacity: 0.96,
    palette: {
      far: "#1f466d",
      middle: "#5f8fb5",
      near: "#85b9d8",
      tonalVariation: 0.025,
    },
  },
  morph: {
    maximumDelay: 0.38,
    targetWidthRatio: 0.68,
    targetHeightRatio: 0.22,
    targetJitterRatio: 0.008,
  },
  pointer: {
    radius: 48,
    force: 80,
    spring: 12,
    damping: 9,
    maximumOffset: 12,
  },
  spatial: {
    wordDepth: 8,
    depthCurve: 2.4,
    dragThreshold: 7,
    dragTravelX: 180,
    dragTravelY: 150,
    yawSoftLimit: 3.5,
    yawHardLimit: 4.2,
    pitchSoftLimit: 2,
    pitchHardLimit: 2.4,
    releaseResponse: 0.5,
    releaseVelocityRetention: 0.18,
    maximumReleaseVelocity: 8,
    scatterPoseGain: 0.24,
    scatterRepulsionGain: 0.36,
    draggingRepulsionGain: 0.64,
  },
} as const;

export const PARTICLE_TIMELINE: readonly TimelinePhase[] = [
  { kind: "hold", shape: "theodore", duration: 5.5 },
  { kind: "morph", to: "scatter", duration: 2.8 },
  { kind: "hold", shape: "scatter", duration: 1.2 },
  { kind: "morph", to: "ouyang", duration: 2.8 },
  { kind: "hold", shape: "ouyang", duration: 4.5 },
  { kind: "morph", to: "scatter", duration: 2.8 },
  { kind: "hold", shape: "scatter", duration: 1.2 },
  { kind: "morph", to: "theodore", duration: 2.8 },
];
